config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  patch '/users/confirmation' => 'devise/confirmations#update', :via => :patch, :as => :update_user_confirmation
  resources :dashboard
  authenticate :user do
    resources :books, only: [:new, :create, :edit, :update, :destroy]
  end
 resources :books do
    collection do
      get 'postings'
    end
  end
  resources :books, only: [:index, :show]

  resources :order_entries
  resources :carts
  resources :wishlists
  resources :wishlist_entries
  
  resources :amazon do
    member do 
        post 'compare'
    end
  end
  
  match '/amazon_price/:id',
    to:   'books#amazon_price',
    via:  'get',
    as:   :amazon_price
 
   match '/order_enteries/:id',
    to:   'dashboard#order_enteries',
    via:  'get',
    as:   :order_enteries
  
  root 'welcome#index'
  get '/MyCart' => 'welcome#mycart'
  get '/WishList' => 'welcome#wishlist'
  get '/Catalog' => 'welcome#catalog'
  get '/PostABook' => 'welcome#postabook'
  get '/books' => 'books#index'
  get '/About' => 'welcome#about'
  get '/Orders' => 'orders#checkout'
  get '/Returns/:id' => 'returns#return'

  
  get '/amazon' => 'amazon#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  helper_method :postings , :orders, :returns
  helper_method :get_order_enteries
  def index
    
  end
  
  def postings
    @books = Book.postings(current_user.id).order("created_at ASC")
   
  end
  
  def orders
    @orders = Order.orders(current_user.id).order("created_at DESC")
  end

  def returns
    @returns = OrderEntry.return_items(current_user.id).order("created_at DESC")
  end
  
  def order_enteries
   @order = Order.find(params[:id])
   @order_enteries = @order.order_entries
   logger.debug (@order_enteries)
   respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def resource_name
    :user
  end

  def resource
    # @resource ||= User.new
    @resource ||= current_user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/dashboard/_order_enteries.html.erb
<div class="modal fade" id="myModalo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
		<div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Order Details</h4>
        </div>
      <div class="modal-body"> 
      	<div class="container">
			<div class="row col-sm-10 title">
				<div class="col-sm-4">
					<p> Book Title</p>
				</div>
				<div class="col-sm-2">
					<p> Quantity </p>
				</div>
				<div class="col-sm-2">
					<p> Total Price </p>
				</div>
				
				</hr>
			</div>
		</div>
      	
		<div class="container">
			
			<% order_enteries.each do |order_entry| %>
			<div class="row col-sm-10">
				<div class="col-sm-4">
					<p> <%= Book.find(order_entry.book_id).title %> </p>
				</div>
				<div class="col-sm-2">
					<p> <%= order_entry.quantity %> </p>
				</div>
				<div class="col-sm-2">
					<p> $<%= order_entry.total_price %> </p>
				</div>
				
				</hr>
			</div>
			
			<% end %>
		</div>
      </div>
		<div class="modal-footer">
		
		</div>
    </div>
  </div>
</div>

app/views/dashboard/_orders.html.erb
<div class="container">
	<% if orders.size ==  0%>
	<div>
		<p> You have no Order History </p>
	</div>
	<% else %>
		<div class="row">
		       <div class="col-sm-6">
		          <h4>Order History</h4>
		          <p></p>
		         </div>
		     	<div class="col-sm-4">
		     	
		     	</div>
	     </div>
	     <hr>
	     <% @count = 0 %>
		<% orders.each do |order| %>
	      	<div class="container row">
	      		<div class="col-sm-2">
	      			<p><%= @count = @count + 1 %></p>
	      			</div>
		       <div class="col-sm-6">
		          <p>Order placed on : <%= order.updated_at %></h4>
		          <p>Total: $ <%= order.total %></p>
		         </div>
		     	<div class="col-sm-4">
		     		<%= link_to "Order Details" , order_enteries_path(order.id) , remote: true %>
		     	</div>
	     	</div>
	     	<hr>
	 	<% end %>
	<% end %>
 
</div>

app/views/dashboard/_postings.html.erb
<div class="container">
	<% if books.size ==  0%>
	<div>
		<p> You have no Books Posted for Rental Or Selling </p>
	</div>
	<% else %>
	<% books.each do |book| %>
      	<div class="container row">
	        <div class="col-sm-2"><img src="<%= book.image_path %>" alt="..." class="img-responsive"/></div>
	        <div class="col-sm-6">
	          <h4 class="nomargin"><%= book.title %></h4>
	          <p>Description: <%= book.description %></p>
	          <p>Quantity: <%= book.quantity %></p>
	          <p>Available for: <%= book.sale_type %></p>
	     	</div>
	     	<div class="col-sm-4">
	     	 	<%= link_to "Edit Posting", edit_book_path(book.id)%><br>
	     	 	<%= link_to 'Delete', book_path(book.id),  method: :delete,  data: { confirm: 'Are you sure?' } %>
	     	 	
	     	</div>
     	</div>
     	<hr>
 	<% end %>
	<% end %>
 
</div>

app/views/dashboard/_returns.html.erb
<div class="container">
	<% if returns.size ==  0%>
	<div>
		<p> You have no Items to Return!</p>
	</div>
	<% else %>
		<div class="row">
		       <div class="col-sm-6">
		          <h4>Return Items</h4>
		          <p></p>
		         </div>
		     	<div class="col-sm-4">
		     	
		     	</div>
	     </div>
	     <hr>
	     <% @count = 0 %>
		<% returns.each do |ret| %>
	      	<div class="container row">
	      	    <div class="col-sm-2"><img src="<%= ret.book.image_path %>" alt="..." class="img-responsive"/></div>
		        <div class="col-sm-6">
		          <h4 class="nomargin"><%= ret.book.title %></h4>
		          <p>Description: <%= ret.book.description %></p>
		     	</div>
	      		<div class="col-sm-6">
		          <p>Order placed on : <%= ret.created_at.to_date.strftime("%d %b, %Y") %></p>
		          <p><strong>Due Date: <%= (ret.created_at.to_date + 10.days).strftime("%d %b, %Y") %></strong></p>
		        </div>
		        <div class="col-sm-6">
		          <p><a href="/Returns/<%= ret.id %>">Return Book</a></p>
		        </div>
	     	</div>
	     	<hr>
	 	<% end %>
	<% end %>
 
</div>

app/views/dashboard/index.html.erb
<div class="container">
	<h4>Welcome to your Dashboard</h4>
	Signed in as <%= current_user.name %>. Not you?
	<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
</div>
<hr/>
<div class="container">
		<div class="">
			<ul class="nav nav-tabs">
				<li role="presentation" class="active" ><a href="#postings" data-toggle="tab">My Postings</a></li>
				<li role="presentation" ><a href="#notifications" data-toggle="tab" >My Orders</a></li>
			  <li role="presentation"><a href="#profile" data-toggle="tab" >Profile</a></li>
			  <li role="presentation"><a href="#returns" data-toggle="tab" >Returns</a></li>
			  
			</ul>
		</div>
		<div class="">
			<div class="tab-content">
				<div class="tab-pane active" id="postings">
					<%= render partial: "postings", object: postings , as: 'books' %>
				</div>
				<div class="tab-pane" id="notifications">
					<%= render partial: "orders", object: orders , as: 'orders' %>
				</div>
				<div class="tab-pane" id="profile">
					<%= render 'users/registrations/edit'%>
				</div>
				<div class="tab-pane" id="returns">
					<%= render partial: "returns", object: returns , as: 'order_entries' %>
				</div>
			
			</div>
			
		</div>

</div>

app/views/dashboard/order_enteries.js.erb
$('body').append('<%= j render partial: "order_enteries" , locals: { order_enteries: @order_enteries } %>');
$('#myModalo').modal('show');
$('#myModalo').on('hidden.bs.modal', function () {
  $(this).remove();
});