config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  patch '/users/confirmation' => 'devise/confirmations#update', :via => :patch, :as => :update_user_confirmation
  resources :dashboard
  authenticate :user do
    resources :books, only: [:new, :create, :edit, :update, :destroy]
  end
 resources :books do
    collection do
      get 'postings'
    end
  end
  resources :books, only: [:index, :show]

  resources :order_entries
  resources :carts
  resources :wishlists
  resources :wishlist_entries
  
  resources :amazon do
    member do 
        post 'compare'
    end
  end
  
  match '/amazon_price/:id',
    to:   'books#amazon_price',
    via:  'get',
    as:   :amazon_price
 
   match '/order_enteries/:id',
    to:   'dashboard#order_enteries',
    via:  'get',
    as:   :order_enteries
  
  root 'welcome#index'
  get '/MyCart' => 'welcome#mycart'
  get '/WishList' => 'welcome#wishlist'
  get '/Catalog' => 'welcome#catalog'
  get '/PostABook' => 'welcome#postabook'
  get '/books' => 'books#index'
  get '/About' => 'welcome#about'
  get '/Orders' => 'orders#checkout'
  get '/Returns/:id' => 'returns#return'

  
  get '/amazon' => 'amazon#index'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :authenticate_user!, except: [:index]
  
  def index
    
  end
  def show
  	@order_entries = current_order.order_entries
  	@total_price = current_order.total
  end


end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart_row.html.erb
<%= form_for order_entry, remote: true do |f| %>
  <%= f.hidden_field :book_id, value: book.id %>
  <tr>
    <td data-th="Product">
      <div class="row">
        <div class="col-sm-2 hidden-xs"><img src="<%= book.image_path %>" alt="..." class="img-responsive"/></div>
        <div class="col-sm-10">
          <h4 class="nomargin"><%= book.title %></h4>
          <p><%= book.description %></p>
        </div>
      </div>
    </td>
    <td data-th="Price" ><%= book.price %></td>
    <td data-th="Quantity">
      <%= f.number_field :quantity, value: order_entry.quantity.to_i, class: "form-control text-center", min: 1, max: book.quantity %>
    </td>
    <td data-th="Purchase Price" class="text-center" ><%= order_entry.unit_cost	 %></td>
    <td data-th="Subtotal" class="text-center"><%= number_to_currency order_entry.total_price %></td>
    <td class="actions" data-th="">
      <%= f.submit "Update", class: "btn btn-info" %>
      <%= link_to "Delete", order_entry, { data: { confirm: "Are you sure you wish to delete the book '#{order_entry.book.title}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>               
    </td>
  </tr>
<% end %>

app/views/carts/_shopping_cart.html.erb
<% if !@order_entry.nil? && @order_entry.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_entry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_entries.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "continue shopping", books_path %> and add some items to your cart.
  </p>
<% else %>
  <table id="cart" class="table table-hover table-condensed">
    <thead>
      <tr>
        <th style="width:40%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:10%">Quantity</th>
        <th style="width:10%" class="text-center">Purchase Price</th>
        <th style="width:10%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
      </tr>
    </thead>
    <tbody>
    <% @order_entries.each do |order_entry| %>
      <%= render 'carts/cart_row', book: order_entry.book, order_entry: order_entry, show_total: true %>
    <% end %>
    </tbody>
    <tfoot>
      <tr class="visible-xs">
        <td class="text-center"><strong>Total <%= @total_price %></strong></td>
      </tr>
      <tr>
      <td><%= link_to "continue shopping", books_path, {:class=>"btn btn-warning"} %></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>Total <%= number_to_currency @total_price %></strong></td>
        <td><a href="/Orders" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
      </tr>
    </tfoot>
  </table>
<% end %>

app/views/carts/show.html.erb
<div class="container shopping-cart">
  <%= render "shopping_cart" %>
</div>